maxmemory 512mb
maxmemory-policy allkeys-lru

save 900 1
save 300 10
save 60 10000

appendonly yes
appendfsync everysec
no-appendfsync-on-rewrite yes
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb

protected-mode yes
bind 0.0.0.0

loglevel notice
logfile ""

timeout 0
tcp-keepalive 300

stop-writes-on-bgsave-error no 
